// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ketgeysguwxleieciyyx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtldGdleXNndXd4bGVpZWNpeXl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NTg3NzIsImV4cCI6MjA3MDAzNDc3Mn0.4wxGxkNTFahHELbh6hcov7gMn0hrkGPPmALiaPlHbr8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});